apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: do-k8s-cluster-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cod-r/bdw-workshop.git
    path: clusters/do-cluster
  destination:
    server: https://3c3cb819-77e0-4aaa-bb9e-3a63d9921c65.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=true
