apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: do-k8s-cluster-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cod-r/bdw-workshop.git
    path: clusters/do-cluster
  destination:
    server: https://62ba9205-6466-4443-bc0e-c8aa46fa5bdc.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=true
