apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: do-k8s-cluster-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cod-r/bdw-workshop.git
    path: clusters/do-cluster
  destination:
    server: https://0858a964-f548-4008-baee-45a82931561e.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=true
